### ISSUE TITLE
Why is the API not working?

### ISSUE THREAD

**Issue by trojanx6** [dmytrostriletskyi/threads-net#18]
I'm trying a piece of code and this error pops up Has the API changed?

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 46, in <module>
  File "<string>", line 9, in __init__
  File "<string>", line 42, in get_user_in
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[Program finished]

THE CODE IS HERE

import requests 
import json

class APİ:
    def __init__(self) -> None:
        self.user ="nacicaner01"#input("Username:").strip()
        self.tempraty_token = self.get_token()
        self.id = self.user_get_id()
        self.get_user_in()
        self.api_url = "https://threads.net/api/graphql"
 
    def get_token(self):
        URL_THREADS_İNSTAGRAM = "https://threads.net/@instagram"
        response = requests.get(url=URL_THREADS_İNSTAGRAM)
        token_find = response.text.find('\"token\"')
        token_extract = response.text[token_find + 9: token_find + 31]
        return token_extract
        
        
    def user_get_id(self):
        response = requests.get(url=f"https://threads.net/@{self.user}")
        user_id_find = response.text.find('\"user_id\"')
        user_id_extract = response.text[user_id_find + 11: user_id_find +17]
        return user_id_extract
        
    def get_user_in(self):
        response = requests.post("https://threads.net/api/graphql",
            headers={
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-IG-App-ID': '238260118697367',
                'X-FB-LSD': self.tempraty_token,
                'Sec-Fetch-Site': 'same-origin',
            },
            data={
                'lsd': self.tempraty_token,
                'variables': json.dumps({
                    'userID': 314216,
                }),
                'doc_id': '6232751443445612',
            },
        )
        print(response.json())

if __name__=="__main__":
    app = APİ()

I'd appreciate your help, I can't figure out how to send a request to the API

**Comment by dmytrostriletskyi** [comment]
Hi, @trojanx6!

Thank you for the interest to the project.

Can you please try new release? I have just dropped v0.0.12 — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.12

If the issue still persist, let me know and I dive into it.

**Comment by dmytrostriletskyi** [comment]
Try v0.0.13, v0.0.12 had a bug — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.13
