### ISSUE TITLE
'PrivateThreadsApi' object has no attribute 'password'

### ISSUE THREAD

**Issue by RealWorldVesper** [dmytrostriletskyi/threads-net#22]
Using V0.014, making a call via private API shows the error "AttributeError: 'PrivateThreadsApi' object has no attribute 'password'".

```
import secretsFile
from threads import Threads
threads = Threads(username=secretsFile.INSTAGRAM_USERNAME, password=secretsFile.INSTAGRAM_PASSWORD)

#Get User ID

def getUserID(uname):

    return(threads.private_api.get_user_id(username=uname))

print(getUserID('realworldvesper'))

Traceback:

Traceback (most recent call last):
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 4, in <module>
    threads = Threads(username=secretsFile.INSTAGRAM_USERNAME, password=secretsFile.INSTAGRAM_PASSWORD)
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/main.py", line 23, in __init__
    self.private_api = PrivateThreadsApi(username=username, password=password)
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/apis/private.py", line 31, in __init__
    self.instagram_api_token = self._get_instagram_api_token()
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/apis/private.py", line 47, in _get_instagram_api_token
    'password': self.password,
AttributeError: 'PrivateThreadsApi' object has no attribute 'password'

**Comment by dmytrostriletskyi** [comment]
Hi, @RealWorldVesper! :) 

Fixed in v0.0.15, sorry for inconvinience.

**Comment by RealWorldVesper** [comment]
@dmytrostriletskyi working now :)

**Comment by RealWorldVesper** [comment]
Resolved.
