### ISSUE TITLE
get_user_id doesn't work<Response [403]>

### ISSUE THREAD

**Issue by developerhost** [dmytrostriletskyi/threads-net#54]
**Description**
get_user_id returns an error even though I entered the correct username and password

```python
def get_user_id(self, username: str) -> int:
        """
        Get a user's identifier.

        Arguments:
            username (str): a user's username.

        Returns:
            The user's identifier as an integer.
        """
        response = requests.get(url=f'{self.INSTAGRAM_API_URL}/users/{username}/usernameinfo/', headers=self.headers)
        # Add these lines
        print('Response:', response)
        print('Response JSON:', response.json())

        user_id_as_string = response.json().get('user').get('pk')
        user_id_as_int = int(user_id_as_string)


        return user_id_as_int
```

Output the response to find out the cause of the error

```
Response: <Response [403]>
Response JSON: {'message': 'login_required', 'error_title': "You've Been Logged Out", 'error_body': 'Please log back in.', 'logout_reason': 2, 'status': 'fail'}
```

I think you have to approve the verification process.

Do you know how?

**Python Version**

Python 3.9.13

**Library Version**

threads-net             0.0.28

**How To Reproduce**

1. Provide a code you execute.

```
from threads import Threads
threads = Threads(username='your_username', password='your_password')

user_id = threads.public_api.get_user_id(username='your_username')
print(user_id)
```

2. Provide full traceback.

```
Response: <Response [403]>
Response JSON: {'message': 'login_required', 'error_title': "You've Been Logged Out", 'error_body': 'Please log back in.', 'logout_reason': 2, 'status': 'fail'}
Traceback (most recent call last):
  File "/Users/kojin/Downloads/workspace/python/threads/test.py", line 2, in <module>
    threads = Threads(username='username', password='password')
  File "/Users/kojin/opt/anaconda3/lib/python3.9/site-packages/threads/main.py", line 27, in __init__
    self.private_api = PrivateThreadsApi(username=username, password=password)
  File "/Users/kojin/opt/anaconda3/lib/python3.9/site-packages/threads/apis/private.py", line 47, in __init__
    self.user_id = self.get_user_id(username=username)
  File "/Users/kojin/opt/anaconda3/lib/python3.9/site-packages/threads/apis/private.py", line 64, in get_user_id
    user_id_as_string = response.json().get('user').get('pk')
```

**Comment by dmytrostriletskyi** [comment]
Hi, @developerhost! 

Thank you for the interest in the project.

First, you do not need to specify username and password if you use only public API:

1. https://github.com/dmytrostriletskyi/threads-net#user-identifier
> If you are going to use only public API, use the following commands:

Second, check this as well — https://github.com/dmytrostriletskyi/threads-net#user-identifier

But as I see, under the hood it calls private API what should not happen. I will investigate it.

**Comment by dmytrostriletskyi** [comment]
Second, seems you might be suspended or banned. Because for me, it works (if we consider this — https://github.com/dmytrostriletskyi/threads-net#user-identifier).

Can you check, you can login to your account normally via web — https://instagram.com?

**Comment by developerhost** [comment]
thank you for your reply.
It worked fine by using the public api.

I can log in without any problem from the web.

**Comment by developerhost** [comment]
excuse me
I want to get followers using threads.private_api.get_user_followers
To do that, you have to pass the username and password in the private_api header.

I would like to know how to break through authentication using private_api.

**Comment by developerhost** [comment]
thank you. I ran it and got the correct result
