### ISSUE TITLE
Compiler error / invalid syntax.

### ISSUE THREAD

**Issue by dongzeli95** [dmytrostriletskyi/threads-net#60]
**Description**
Compiler error / invalid syntax.

**Python Version**
`3.8.16`

**Library Version**

`threads-net==0.0.44`

**How To Reproduce**

1. Provide a code you execute.
```
    def like_threads(self):
        # Get the followings
        user_id = self.threads.private_api.get_user_id(username=self.username)
        user_following_response = self.threads.private_api.get_user_following(id=user_id)
        user_following = user_following_response.get('users', [])

        # For each following, get their threads and like them
        for user in user_following:
            user_id = user.get('pk')  # Get user's primary key (pk)
            if user_id:
                user_threads = self.threads.public_api.get_user_threads(id=user_id)
                print(user_threads)
def main():
    test_threads()

def test_threads():
    manager = ThreadManager()
    manager.like_threads()
```

3. Provide full traceback.
```
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main()
  File "main.py", line 31, in main
    test_threads()
  File "main.py", line 35, in test_threads
    manager.like_threads()
  File "/Users/dongzeli/Sweat/biji/biji-ai/app/aigc/threads/threads_manager.py", line 31, in like_threads
    user_threads = self.threads.public_api.get_user_threads(id=user_id)
  File "/Users/dongzeli/anaconda3/envs/biji-ai/lib/python3.8/site-packages/threads/apis/public.py", line 114, in get_user_threads
    headers = self.default_headers | {
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by dmytrostriletskyi** [comment]
As I understood, in `Python 3.8` there is no `|` syntax for merging dictionaries.

If you check the README, it says the library support >= 3.9.

<img width="926" alt="Screenshot 2023-07-14 at 11 04 51" src="https://github.com/dmytrostriletskyi/threads-net/assets/22666467/6f48385e-af01-4313-88d5-eebccdcf0665">

Can you try 3.9 or above?

**Comment by dongzeli95** [comment]
Yes good callout, I've upgraded my python dependency and it worked now. Thanks!
