### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' (on private_api)

### ISSUE THREAD

**Issue by dongzeli95** [dmytrostriletskyi/threads-net#65]
**Description**

AttributeError: 'NoneType' object has no attribute 'get' (on private_api)

Note that locally I can run the api just fine, but when i deploy the application on cloud, the error persists. My gut feeling tells me this have something to do with the different geolocations the API got called from.

**Python Version**

`3.10`

**Library Version**

`threads-net==0.0.49`

**How To Reproduce**

1. Provide a code you execute.

```
    def __init__(self):
        INSTAGRAM_USERNAME = os.environ.get('INSTAGRAM_USERNAME')
        INSTAGRAM_PASSWORD = os.environ.get('INSTAGRAM_PASSWORD')
        self.username = INSTAGRAM_USERNAME
        self.password = INSTAGRAM_PASSWORD
        self.logger = logging.getLogger('haha')
        self.logger.error(f"username: {INSTAGRAM_USERNAME}")
        self.logger.error(f"password: {INSTAGRAM_PASSWORD}")
        self.threads = Threads(username=self.username, password=self.password)
```

2. Provide full traceback.

```
Traceback (most recent call last):
  File "/usr/local/bin/goblet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/goblet/cli.py", line 455, in run_job
    app(name, int(task_id))
  File "/usr/local/lib/python3.10/site-packages/goblet/resource_manager.py", line 136, in __call__
    response = self.handlers["jobs"](request, context)
  File "/usr/local/lib/python3.10/site-packages/goblet/handlers/jobs.py", line 54, in __call__
    return job["func"](task_id)
  File "/app/main.py", line 14, in like_threads
    manager = ThreadManager()
  File "/app/app/threads_app/threads_manager.py", line 19, in __init__
    self.threads = Threads(username=self.username, password=self.password)
  File "/usr/local/lib/python3.10/site-packages/threads/main.py", line 34, in __init__
    self.public_api = PublicThreadsApi()
  File "/usr/local/lib/python3.10/site-packages/threads/apis/public.py", line 29, in __init__
    self.threads_api_token = self._get_threads_api_token()
  File "/usr/local/lib/python3.10/site-packages/threads/apis/public.py", line 235, in _get_threads_api_token
    token_key_value = re.search('LSD",\\[\\],{"token":"(.*?)"},\\d+\\]', response.text).group()
AttributeError: 'NoneType' object has no attribute 'group'
```

3. Provide a link to `Threads` and/or `Instagram` account if relevant
slog.fitness

I don't have 2FA authentication enabled on my account, and I can see this issue is exactly the same as mine.

https://github.com/dmytrostriletskyi/threads-net/issues/37

**Comment by dongzeli95** [comment]
```
"Traceback (most recent call last):
  File "/usr/local/bin/goblet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/goblet/cli.py", line 455, in run_job
    app(name, int(task_id))
  File "/usr/local/lib/python3.10/site-packages/goblet/resource_manager.py", line 136, in __call__
    response = self.handlers["jobs"](request, context)
  File "/usr/local/lib/python3.10/site-packages/goblet/handlers/jobs.py", line 54, in __call__
    return job["func"](task_id)
  File "/app/main.py", line 14, in like_threads
    manager = ThreadManager()
  File "/app/app/threads_app/threads_manager.py", line 19, in __init__
    self.threads = Threads(username=self.username, password=self.password)
  File "/usr/local/lib/python3.10/site-packages/threads/main.py", line 34, in __init__
    self.public_api = PublicThreadsApi()
  File "/usr/local/lib/python3.10/site-packages/threads/apis/public.py", line 29, in __init__
    self.threads_api_token = self._get_threads_api_token()
  File "/usr/local/lib/python3.10/site-packages/threads/apis/public.py", line 235, in _get_threads_api_token
    token_key_value = re.search('LSD",\\[\\],{"token":"(.*?)"},\\d+\\]', response.text).group()
AttributeError: 'NoneType' object has no attribute 'group'"
```

This is another error associated with it.

**Comment by dmytrostriletskyi** [comment]
You log the Instagram username and passord,just to double check, those are logged abd there is non-empty values, correct?

**Comment by dongzeli95** [comment]
Yes double checked just to be sure. They are valid values, same as the ones I used locally.

**Comment by dongzeli95** [comment]
For instagram apis library, they have this mechanism to set login settings [[ref](https://adw0rd.github.io/instagrapi/usage-guide/interactions.html)]:

```
In order for Instagram [to trust you more](https://github.com/adw0rd/instagrapi/discussions/220), you must always login from one device and one IP (or from a subnet):

cl = Client()
cl.login(USERNAME, PASSWORD)
cl.dump_settings('/tmp/dump.json')
Next time:

cl = Client()
cl.load_settings('/tmp/dump.json')
cl.login(USERNAME, PASSWORD)
cl.get_timeline_feed()  # check session
```

The result look something like this:

```
{
    "uuids": {
        "phone_id": "YOUR_PHONE_ID",
        "uuid": "",
        "client_session_id": "",
        "advertising_id": "",
        "android_device_id": "",
        "request_id": "",
        "tray_session_id": ""
    },
    "mid": "ZLYiUgABAAFRlYTy1fp4j_WuMQiC",
    "ig_u_rur": null,
    "ig_www_claim": null,
    "authorization_data": {
        "ds_user_id": "",
        "sessionid": ""
    },
    "cookies": {},
    "last_login": 1689657948.115246,
    "device_settings": {
        "app_version": "269.0.0.18.75",
        "android_version": 26,
        "android_release": "8.0.0",
        "dpi": "480dpi",
        "resolution": "1080x1920",
        "manufacturer": "OnePlus",
        "device": "devitron",
        "model": "6T Dev",
        "cpu": "qcom",
        "version_code": "314665256"
    },
    "user_agent": "Instagram 269.0.0.18.75 Android (26/8.0.0; 480dpi; 1080x1920; OnePlus; 6T Dev; devitron; qcom; en_US; 314665256)",
    "country": "US",
    "country_code": 1,
    "locale": "en_US",
    "timezone_offset": -14400
}
```

I guess this will help threads as well to recognize a certain user and give them access? @dmytrostriletskyi

**Comment by dongzeli95** [comment]
This is fixed by using 

`Threads(settings=settings, username=self.username, password=self.password)`
